[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.9.1"
log = "0.4.17"
tokio = { version = "1.20.1", features = ["full"] }
